export interface Game2v2 {
    id: string,
    competition_id: string,
    round: number,
    team1_id: string,
    team2_id: string,
    winner_id: string,
    team1bot1_id: string,
    team1bot2_id: string,
    team2bot1_id: string,
    team2bot2_id: string,
    team1bot1_survived: boolean,
    team1bot2_survived: boolean,
    team2bot1_survived: boolean,
    team2bot2_survived: boolean,
    public: boolean,
    additional_data: string,
    created: string,
}